DEFAULT_IMAGE_NAME = "152413574287.dkr.ecr.us-east-1.amazonaws.com/athena-query-runner"
DEFAULT_IMAGE_TAG = "1.0.0"
DEFAULT_DISPLAY_NAME = "Parse Datetime"
DEFAULT_CONTAINER_NAME = "main"

DEFAULT_MEMORY_REQUEST = '10Mi'
DEFAULT_MEMORY_LIMIT = '20Mi'
DEFAULT_CPU_REQUEST = '100m'
DEFAULT_CPU_LIMIT = '200m'

STARTUP_COMMAND = "run"

OUTPUT_PATH = "/data/output.json"

AWS_ACCESS_KEY_ID_ENV = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV = "AWS_SECRET_ACCESS_KEY"
AWS_REGION_ENV = "AWS_REGION"

DEFAULT_LOG_LEVEL = "info"
DEFAULT_QUERY_COMPLETION_POOLING_TIME = 3
DEFAULT_DATABASE = "default"
DEFAULT_S3_OUTPUT_LOCATION = "s3://aws-athena-query-results-748130356537-us-east-1"

DEFAULT_AWS_SECRET_NAME = "aws-mlops-bot"
